### ISSUE TITLE
Why not use requests 

### ISSUE THREAD

**Issue by NeedNot** [0x26e/HypixelProjects#1]
I'm not a python expert but your method of getting the data from hypixel is too confusing

**Comment by NeedNot** [comment]
Also I would make a repository for each of your projects other wise downloading it would be annoying as you also have to download other stuff too

**Comment by 0x26e** [comment]
`requests` is a synchronous library
`grequests` is the asynchronous version of the library.

We use `grequests > requests` as it gives us access to calling multiple accounts at once without it incrementally increasing computing time. This will be very useful later on down the line for some of the stat sections (as there are legacy stats that are no longer obtainable, so we need to combine dicts from multiple accounts to (hopefully) get all of them.
